### ISSUE TITLE
Static Resource containing images is not loading locally only on the Server

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/lwc-dev-server-feedback#4] opened 2019-10-05 10:15 UTC
I have a series of icons stored as a public static resource. I zipped the files and upload it to Salesforce. Then I retrieved it to my sfdx project folder using the sfdx pull command to use it locally. The link is generated correctly but the image does not render. But when I push my code to the scratch org I can see the images being rendered. Follow bellow an image showing the same lwc in the org and locally. You will see that the image loads in the server but not locally.

**Screenshots**
![image](https://user-images.githubusercontent.com/55927613/66253512-6b53aa80-e761-11e9-82b1-99fb526c51e4.png)

![image](https://user-images.githubusercontent.com/55927613/66253515-727ab880-e761-11e9-8f06-ebe68d1dd838.png)

**Desktop 
 - OS: Windows 10
 - Browser: Chrome
 - Version: Last version

**Comment by AllanOricil** [comment] 2019-10-07 18:16
I found the issue. Whenever you pull a static resource from an org, stop and restart the local server. It does not have hotreload on it for staticresources. 
It would be a good idea to implement it.

**Comment by KelvinHuangDZ** [comment] 2020-02-23 23:37
I have similar issue, my Static Resource has a global css.
Whenever i make changes to the css file, it's not reflected on the page.

**Comment by mysticflute** [comment] 2020-05-05 23:54
dupe of #22

**Closed by mysticflute** 2020-05-05 23:54 UTC
Labels: type:bug-p3
