### ISSUE TITLE
Local dev server error with API version 49 #48

### ISSUE THREAD

**Issue by proogramer** [forcedotcom/lwc-dev-server-feedback#69] opened 2020-06-02 07:23 UTC
Uncaught Error: Could not resolve entry (force/lds)
    at error (:3333/home/pk/.local/share/sfdx/node_modules/rollup/dist/rollup.js:3460)
    at :3333/home/pk/.local/share/sfdx/node_modules/rollup/dist/rollup.js:21359
utils.js:7 Uncaught (in promise) Error: Cannot resolve dependency 'lightning/verticalNavigationSection'
    at assert$1 (utils.js:7)
    at Object.assign.__circular__ (moduleRegistry.js:161)
    at resolveCircularModuleDependency (engine.js:738)
    at c (engine.js:3432)
    at tmpl$1 (home.js:240)
    at evaluateTemplate (engine.js:4057)
    at engine.js:4228
    at runWithBoundaryProtection (engine.js:6106)
    at invokeComponentRenderMethod (engine.js:4218)
    at renderComponent (engine.js:4357)

![Screenshot from 2020-06-01 12-34-25](https://user-images.githubusercontent.com/35003003/83491756-e081a600-a4cf-11ea-901c-4ce1cb1d74d2.png)
![Screenshot from 2020-06-01 12-39-00](https://user-images.githubusercontent.com/35003003/83491788-ee372b80-a4cf-11ea-84d7-a1cc5c4f8472.png)

I am getting this issue when I connect to my sandbox
The sandbox API version is 49.0 and lwc API version is 48.0 
How should I update my lwc API version...
can anyone please help .....

**Comment by lcampos** [comment] 2020-06-03 15:34
Hi @proogramer thanks for opening this issue. The root cause is a change in the new platform release breaks some of the functionality in local dev. We are working on a fix and will have it out end of day today or tomorrow.
Since this is the same as #68 I'll close this one since the conversation there include more people.
Thanks again for opening this and sorry for the inconvenience this has caused.

**Closed by lcampos** 2020-06-03 15:34 UTC

**Comment by proogramer** [comment] 2020-06-04 05:56
Still, I am getting the same error.....??
