### ISSUE TITLE
Can't install the LWC Local Development Server - Response code 403 

### ISSUE THREAD

**Issue by LiveLikeLastDay** [forcedotcom/lwc-dev-server-feedback#160] opened 2023-09-08 12:05 UTC
### Summary

Can't install the LWC Local Development Server due to HTTPError: Response code 403 (Forbidden)

### Steps To Reproduce:

1.  Run sfdx plugins:install @salesforce/lwc-dev-server by following https://developer.salesforce.com/tools/vscode/en/localdev/set-up-lwc-local-dev

### Expected result

Local dev server is installed.

### Actual result
Polling for new version(s) to become available on npm... done
    HTTPError: Response code 403 (Forbidden)
    Code: ERR_NON_2XX_3XX_RESPONSE

### Additional information

**Salesforce Extension Version in VS Code**: v58.14.1

**SFDX CLI Version**:sfdx-cli/7.209.6 win32-x64 node-v18.15.0

**OS and version**: Windows 11 [Version 10.0.22621.2215]

**Comment by Varout** [comment] 2023-09-14 14:11
I have also experienced this today using WSL on Windows 10.
Steps To Reproduce & Expected Results are the same.

### Actual Result

```bash
Polling for new version(s) to become available on npm... done
    HTTPError: Response code 403 (Forbidden)
    Code: ERR_NON_2XX_3XX_RESPONSE
```

### Additional Information
- WSL OS: Ubuntu 22.04.3 LTS
- CLI installed via NPM: `@salesforce/cli@2.7.11`
- Tried the installation on another machine with the same WSL OS, NPM install, and network: Same result

**Comment by RaymondChuh** [comment] 2023-09-14 23:19
Hi all, I have been trying to install the local dev server in last couple day but experiencing the same issue.

**Summary**
Can't install the LWC Local Development Server due to HTTPError: Response code 403 (Forbidden)

**Steps To Reproduce**:
1. Run sfdx plugins:install @salesforce/lwc-dev-server by following https://developer.salesforce.com/tools/vscode/en/localdev/set-up-lwc-local-dev

**Expected result**
Local dev server is installed.

**Actual result**
Polling for new version(s) to become available on npm... done
HTTPError: Response code 403 (Forbidden)
Code: ERR_NON_2XX_3XX_RESPONSE

**Additional information**
- Salesforce Extension Pack Version in VS Code: v58.14.2
- SFDX CLI Version:@salesforce/cli/2.7.11 darwin-arm64 node-v18.15.0
- OS and version: macOS 12.3 (21E230)

**Comment by mshanemc** [comment] 2023-09-15 18:46
thanks for letting us know.  This is now fixed and you can install the plugin again.

Sorry, y'all!

**Closed as completed by mshanemc** 2023-09-15 18:46 UTC
