### ISSUE TITLE
I am a Front End Developer. As a developer it's quite irritating to see the display output windowof mobile size. It would be great if the local output window is same as it is displayed inside the org. Which means Utilizing full screen width and this will make inspection of element or bugs easy.

### ISSUE THREAD

**Issue by Sparsh25** [forcedotcom/lwc-dev-server-feedback#61] opened 2020-04-28 02:40 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mysticflute** [comment] 2020-05-05 23:41
Duplicate of  #26

**Closed by mysticflute** 2020-05-05 23:41 UTC
Labels: type:feature
